<?php
$z[0]=Array("field","",290,309);
$z[0][4]['name']="title";
$z[1]=Array("global","",310,336);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",377,406);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",446,504);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",861,897);
$z[4][4]['filename']="head2.htm";
$z[5]=Array("include","",4912,4949);
$z[5][4]['filename']="bottom.htm";

?>