<?php
$z[0]=Array("field","",290,309);
$z[0][4]['name']="title";
$z[1]=Array("global","",310,336);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",377,406);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",446,504);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",862,897);
$z[4][4]['filename']="head.htm";
$z[5]=Array("type"," [field:typelink /]",1015,1067);
$z[5][4]['typeid']="11";
$z[6]=Array("type"," \r\n    <div class=\"box_n\">\r\n    	<div class=\"diyx1\"><img src=\"[field:typeimg /]\">[field:description /]</div>\r\n    </div>\r\n    ",1122,1281);
$z[6][4]['typeid']="11";
$z[7]=Array("type"," [field:typelink /]",1413,1465);
$z[7][4]['typeid']="12";
$z[8]=Array("arclist","\r\n      	<li><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" width=\"100\" height=\"72\"><span>[field:title/]</span><p>[field:description function='cn_substr(@me,250)'/]...</p>\r\n        <p>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</p></a></li>\r\n        ",1576,1898);
$z[8][4]['titlelen']="42";
$z[8][4]['row']="5";
$z[8][4]['typeid']="12";
$z[9]=Array("type"," [field:typelink /]",2057,2109);
$z[9][4]['typeid']="13";
$z[10]=Array("arclist","\r\n      	<li><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" width=\"100\" height=\"72\"><span>[field:title/]</span><p>[field:description function='cn_substr(@me,250)'/]...</p>\r\n        <p>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</p></a></li>\r\n        ",2220,2542);
$z[10][4]['titlelen']="42";
$z[10][4]['row']="5";
$z[10][4]['typeid']="13";
$z[11]=Array("include","",2583,2620);
$z[11][4]['filename']="footer.htm";
$z[12]=Array("include","",2630,2667);
$z[12][4]['filename']="bottom.htm";

?>