<?php
$z[0]=Array("field","",290,309);
$z[0][4]['name']="title";
$z[1]=Array("global","",310,336);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",377,406);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",446,504);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",859,894);
$z[4][4]['filename']="head.htm";
$z[5]=Array("type"," [field:typelink /]",1012,1063);
$z[5][4]['typeid']="8";
$z[6]=Array("type","\r\n      <div class=\"diyx3\"> <a href=\"[field:typelink /]\"><img src=\"[field:typeimg /]\" >[field:content /]</a> </div>\r\n      ",1138,1293);
$z[6][4]['typeid']="8";
$z[7]=Array("type"," [field:typelink /]",1428,1479);
$z[7][4]['typeid']="9";
$z[8]=Array("type","\r\n      <div class=\"diyx2\"> <a href=\"[field:typelink /]\"><img src=\"[field:typeimg /]\">[field:content /]</a> </div>\r\n      ",1554,1708);
$z[8][4]['typeid']="9";
$z[9]=Array("type"," [field:typelink /]",1844,1896);
$z[9][4]['typeid']="10";
$z[10]=Array("type","\r\n      <div class=\"diyx2\"> <a href=\"[field:typelink /]\"><img src=\"[field:typeimg /]\">[field:content /] </a> </div>\r\n      ",1970,2126);
$z[10][4]['typeid']="10";
$z[11]=Array("include","",2147,2184);
$z[11][4]['filename']="footer.htm";
$z[12]=Array("include","",2192,2229);
$z[12][4]['filename']="bottom.htm";

?>