<?php
$z[0]=Array("field","",374,393);
$z[0][4]['name']="title";
$z[1]=Array("global","",394,420);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",461,490);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",530,588);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("type","[field:seotitle /]",973,1014);
$z[5]=Array("field","",1068,1090);
$z[5][4]['name']="typeimg";
$z[6]=Array("field","",1175,1196);
$z[6][4]['name']="content";

?>