<?php
$z[0]=Array("global","",290,316);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",357,384);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",424,454);
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",811,848);
$z[3][4]['filename']="header.htm";
$z[4]=Array("arclist","\r\n      	<li><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" alt=\"[field:fulltitle/]\" class=\"imgall\"></a></li>\r\n      ",929,1112);
$z[4][4]['flag']="f";
$z[4][4]['typeid']="18";
$z[4][4]['row']="5";
$z[5]=Array("type"," [field:typelink /]",1217,1269);
$z[5][4]['typeid']="14";
$z[6]=Array("type"," [field:typelink /]",1398,1450);
$z[6][4]['typeid']="15";
$z[7]=Array("type"," [field:typelink /]",1588,1640);
$z[7][4]['typeid']="16";
$z[8]=Array("type"," [field:typelink /]",1772,1824);
$z[8][4]['typeid']="17";
$z[9]=Array("type"," [field:typelink /]",1976,2027);
$z[9][4]['typeid']="3";
$z[10]=Array("type"," [field:typelink /]",2119,2170);
$z[10][4]['typeid']="2";
$z[11]=Array("type"," [field:typelink /]",2375,2426);
$z[11][4]['typeid']="4";
$z[12]=Array("include","",2518,2555);
$z[12][4]['filename']="bottom.htm";

?>